### ISSUE TITLE
unsafe rooting

### ISSUE THREAD

**Issue by stevengj** [Suavesito-Olimpiada/LibTeXPrintf.jl#11]
This is not correct:
```jl
function texsetfont(font::String)
    if font ∉ texfonts()
        throw(ArgumentError("\"$font\" not in $(texfonts())"))
    end
    GC.@preserve font begin
        libtexprintf.TEXPRINTF_FONT[] = pointer(font)
    end
    return font
end
```
The problem is that `GC.@preserve font` only preserves the `font` object for *that `begin … end` statement*.   Once the function returns, Julia may freely deallocate the `font` string, at which point the the `TEXPRINTF_FONT[]` pointer will be garbage.

Suggested solution:

1. Have a `const` global variable `TEXFONTS` holding an array of allowed fonts (either initialized in `__init__` by calling `texfonts()`, or just making a constant list — I don't think this list is changing, and it can always be updated if the upstream library changes.
2. Set `libtexprintf.TEXPRINTF_FONT[]` to `pointer(TEXFONTS[i])` where `i` is the index of the specified font.

**Comment by Suavesito-Olimpiada** [comment]
There is already a `const TEXFONTS`, so the only thing left to change is `pointer(font)` to `pointer(TEXFONTS[i])`.
