### ISSUE TITLE
License of combined work is GPL

### ISSUE THREAD

**Issue by stevengj** [Suavesito-Olimpiada/LibTeXPrintf.jl#6]
Since the original C library is [under the GNU GPL](https://github.com/bartp5/libtexprintf/blob/77595060141ac1da3d146c62eed5fe3113811cc7/COPYING), the combined work of this package and the underlying library must be GPLed.

Technically, your Julia wrapper code could be MIT licensed, but the combined work of your wrappers and the underlying GPL library must be GPL.  i.e. anyone using this library must do so according to the GPL terms.  So it would be clearer to change your LICENSE.md file to the GPL.  (Otherwise someone using your Julia wrapper might be misled into thinking that they can do so under the MIT license.)  Or at the very least your LICENSE file or something should mention that the underlying library (and hence the combined work) is GPLed, but this may be confusing; it seems clearer just to make your LICENSE.md file GPL (since you can't really use the wrapper code without the underlying GPL library anyway).

(According to the [FSF and their legal counsel](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL), if you write a program that links to a library that is GPL, e.g. a program using LibTeXPrintf, then the combined work is GPL, [even if you link dynamically](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins) as Julia does.)

**Comment by Suavesito-Olimpiada** [comment]
Hey!

Thanks for the commentary. You're completely correct about the licence terms. I'll change them to GPL, as I think is the easiest course of action.
