### ISSUE TITLE
transfer to JuliaStrings

### ISSUE THREAD

**Issue by stevengj** [Suavesito-Olimpiada/LibTeXPrintf.jl#7]
Might be worth transferring this to https://github.com/JuliaStrings org to allow additional maintainers?

**Comment by Suavesito-Olimpiada** [comment]
I don't know how to transfer repositories, but gladly. I think it would be sensible to wait until I fix the licence and upgrade upstream.

**Comment by stevengj** [comment]
Great, when you are ready I can add you to the JuliaStrings organization and then you can just click Transfer in your Settings: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization

**Comment by Suavesito-Olimpiada** [comment]
If you can and have time, I can do it today. Also, thanks for the link to the docs.

**Comment by stevengj** [comment]
I sent you an invite to JuliaStrings

**Comment by Suavesito-Olimpiada** [comment]
I accepted it and moved the repo.
