### ISSUE TITLE
LaTeXStrings support

### ISSUE THREAD

**Issue by stevengj** [Suavesito-Olimpiada/LibTeXPrintf.jl#8]
The [current `strip` behavior for a `LaTeXString`](https://github.com/Suavesito-Olimpiada/LibTeXPrintf.jl/blob/6c83094d691486cfbb306999dd971a669218d2ef/src/LibTeXPrintf.jl#L259) doesn't seem quite right:

> If `format isa LaTeXString`, then the keyword `clean` is present. When `clean=true` then `format` is  changed for `strip(format, '\$')`, stripping of the initial and ending `'\$'`.

A single LaTeXString can, in principle, contain multiple equations delimited by `$` or `$$`, e.g. `L"$x+y$ and $e^x$ are formulas"`, so the right behavior is to apply `texprintf` to each `$...$` substring, probably with a regex search/replace.

However, in the longer term my suggestion would be to remove the LaTeXString support completely.  Instead, LaTeXStrings.jl can  make this package an [optional dependency](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)), and use it automatically for its [multiline/3-arg `show` method](https://docs.julialang.org/en/v1/manual/types/#man-custom-pretty-printing) for `display` *if* LibTeXPrintf is loaded.

**Comment by Suavesito-Olimpiada** [comment]
Yup, it was a fast and hacky solution. Although I did think about it.

Each `$...$` can be `texprintf`ed to multiple lines. In principle, I would like to check which ones are, and format the rest of the line in a text box to center it wrt the TeX displayed. But for that I need to write a parser to detect which of the `$` does form a new section of math, and which ones do not.

Another thing is that I would like to detect `$$`, to be able to treat them as a new line math section, and print them in a new line.

**Comment by Suavesito-Olimpiada** [comment]
About the longer term suggestion, I think that it is really sensible. With the support of extensions, I think this is the correct way to carry on.

**Comment by Suavesito-Olimpiada** [comment]
This package side is fixed by #14, the work needed must be done in LaTeXStrings.jl.
